// react/lib/components/BxTagSelector/BxTagSelector.tsx
import React, { ChangeEvent } from 'react';
import { defaultProps, type Props } from './BxTagSelector.props';
import styles from './BxTagSelector.module.css';
import { getClassName } from '../../utils/getClassName';

export function BxTagSelector({ children, ...props }: Partial<Props>) {
  const {
    onAdd = () => null,
    onAuxClick = () => null,
    onClick = () => null,
    onCreate = () => null,
    onDelete = () => null,
    onEnter = () => null,
    onInput = () => null,
    list = defaultProps.list,
    placeholder = defaultProps.placeholder,
    displayFieldName = defaultProps.displayFieldName,
    displayFieldLink = defaultProps.displayFieldLink,
    displayFieldIcon = defaultProps.displayFieldIcon,
    defaultIcon = defaultProps.defaultIcon,
    textAddButton = defaultProps.textAddButton,
    textCreateButton = defaultProps.textCreateButton,
    textMoreButton = defaultProps.textMoreButton,
    textChangeButton = defaultProps.textChangeButton,
    showAddButton = defaultProps.showAddButton,
    showCreateButton = defaultProps.showCreateButton,
    showInputText = defaultProps.showInputText,
    clickable = defaultProps.clickable,
    multiple = defaultProps.multiple,
    inline = defaultProps.inline,
    icon = defaultProps.icon,
  } = props;

  const [text, setText] = React.useState<string>('');

  function getImageUrl(icon?: string) {
    return icon ?? new URL(`./icons/${defaultIcon}.svg`, import.meta.url).href;
  }

  function onClickLink(
    e: React.MouseEvent,
    eventName: 'click' | 'auxclick',
    key: number,
    item: any,
  ) {
    if (clickable) {
      e.preventDefault();
      if (eventName === 'click') {
        onClick(key, item);
      } else if (eventName === 'auxclick') {
        onAuxClick(key, item);
      }
    }
  }

  const Items = list.map((item: any, key: number) => (
    <div
      className={getClassName('ui-tag-selector-item ui-tag-selector-tag', {
        'ui-tag-selector-tag--has-avatar': icon,
      })}
      key={key}
    >
      {clickable ? (
        <a
          className="ui-tag-selector-tag-content"
          href={item[displayFieldLink] ? item[displayFieldLink] : '#'}
          target="_blank"
          onClick={!item[displayFieldLink] ? (e) => onClickLink(e, 'click', key, item) : () => {}}
          onAuxClick={
            !item[displayFieldLink] ? (e) => onClickLink(e, 'auxclick', key, item) : () => {}
          }
        >
          <div className={['ui-tag-selector-tag-title', styles['title']].join(' ')}>
            {item[displayFieldName]}
          </div>
        </a>
      ) : (
        <div className="ui-tag-selector-tag-content">
          {icon ? (
            <div
              className="ui-tag-selector-tag-avatar"
              style={{
                backgroundImage: `url(${getImageUrl(item[displayFieldIcon])})`,
              }}
            ></div>
          ) : (
            children
          )}
          <div className={['ui-tag-selector-tag-title', styles['title']].join(' ')}>
            {item[displayFieldName]}
          </div>
        </div>
      )}
      <div className="ui-tag-selector-tag-remove" onClick={() => onDelete(key, item)}></div>
    </div>
  ));

  function onKeyUp(e: React.KeyboardEvent<HTMLInputElement>, text: string) {
    if (e.key === 'Enter') onEnter(text);
  }

  function onInputText(e: React.ChangeEvent<HTMLInputElement>) {
    setText(e.target.value);
    onInput(e.target.value);
  }

  return (
    <div
      className={getClassName('ui-tag-selector-outer-container', { [styles['inline']]: inline })}
    >
      <div className="ui-tag-selector-container">
        <div className="ui-tag-selector-items">
          {Items}
          <input
            type="text"
            className={getClassName('ui-tag-selector-item ui-tag-selector-text-box', {
              'ui-tag-selector-item-hidden': !showInputText,
            })}
            autoComplete="off"
            placeholder={placeholder}
            value={text}
            onInput={(e: ChangeEvent<HTMLInputElement>) => onInputText(e)}
            onKeyUp={(e) => onKeyUp(e, text)}
          />
          {showAddButton ? (
            <span
              className="ui-tag-selector-item ui-tag-selector-add-button"
              onClick={() => onAdd(text)}
            >
              <span className="ui-tag-selector-add-button-caption">
                {!list.length ? textAddButton : multiple ? textMoreButton : textChangeButton}
              </span>
            </span>
          ) : (
            ''
          )}
        </div>
        <div
          className={getClassName('ui-tag-selector-create-button', {
            'ui-tag-selector-item-hidden': !showCreateButton,
          })}
          onClick={() => onCreate()}
        >
          <span className="ui-tag-selector-create-button-caption">{textCreateButton}</span>
        </div>
      </div>
    </div>
  );
}

// vue/src/components/BxTagSelector.vue
<template>
  <div
    class="ui-tag-selector-outer-container"
    :class="{
      [$style['inline']]: props.inline,
    }"
  >
    <div class="ui-tag-selector-container">
      <div class="ui-tag-selector-items">
        <div
          v-for="(item, key) in props.list"
          :key="key"
          class="ui-tag-selector-item ui-tag-selector-tag"
          :class="{
            'ui-tag-selector-tag--has-avatar': props.icon,
          }"
        >
          <component
            :is="props.clickable ? 'a' : 'div'"
            class="ui-tag-selector-tag-content"
            :href="
              props.clickable
                ? item[props.displayFieldLink]
                  ? item[props.displayFieldLink]
                  : '#'
                : null
            "
            :target="props.clickable ? '_blank' : null"
            @click="
              props.clickable && !item[props.displayFieldLink]
                ? onClick($event, 'click', key, item)
                : null
            "
            @auxclick="
              props.clickable && !item[props.displayFieldLink]
                ? onClick($event, 'auxclick', key, item)
                : null
            "
          >
            <div
              v-if="props.icon"
              class="ui-tag-selector-tag-avatar"
              :style="`background-image: url(${getImageUrl(item[props.displayFieldIcon])});`"
            ></div>
            <slot v-else></slot>
            <div class="ui-tag-selector-tag-title" :class="[$style['title']]">
              {{ item[props.displayFieldName] }}
            </div>
          </component>
          <div class="ui-tag-selector-tag-remove" @click="$emit('delete', key, item)"></div>
        </div>
        <input
          type="text"
          class="ui-tag-selector-item ui-tag-selector-text-box"
          :class="{
            'ui-tag-selector-item-hidden': !props.showInputText,
          }"
          autocomplete="off"
          :placeholder="props.placeholder"
          v-model="text"
          @input="$emit('input', text)"
          @keyup.enter="$emit('enter', text)"
        />
        <span
          v-if="props.showAddButton"
          class="ui-tag-selector-item ui-tag-selector-add-button"
          @click="$emit('add', text)"
        >
          <span class="ui-tag-selector-add-button-caption">
            {{
              !props.list.length
                ? props.textAddButton
                : props.multiple
                  ? props.textMoreButton
                  : props.textChangeButton
            }}
          </span>
        </span>
      </div>
      <div
        class="ui-tag-selector-create-button"
        :class="{
          'ui-tag-selector-item-hidden': !props.showCreateButton,
        }"
        @click="$emit('create')"
      >
        <span class="ui-tag-selector-create-button-caption">{{ props.textCreateButton }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { type PropType, ref } from 'vue';
import { loadStyles } from '@/utils/loadStyles';
import { defaultProps, type ItemType } from './BxTagSelector.props';

loadStyles();

const props = defineProps({
  list: {
    type: Array as PropType<ItemType[]>,
    default: () => defaultProps.list,
  },
  placeholder: {
    type: String as PropType<string>,
    default: defaultProps.placeholder,
  },
  displayFieldName: {
    type: String as PropType<string>,
    default: defaultProps.displayFieldName,
  },
  displayFieldLink: {
    type: String as PropType<string>,
    default: defaultProps.displayFieldLink,
  },
  displayFieldIcon: {
    type: String as PropType<string>,
    default: defaultProps.displayFieldIcon,
  },
  defaultIcon: {
    type: String as PropType<string>,
    default: defaultProps.defaultIcon,
  },
  textAddButton: {
    type: String as PropType<string>,
    default: defaultProps.textAddButton,
  },
  textCreateButton: {
    type: String as PropType<string>,
    default: defaultProps.textCreateButton,
  },
  textMoreButton: {
    type: String as PropType<string>,
    default: defaultProps.textMoreButton,
  },
  textChangeButton: {
    type: String as PropType<string>,
    default: defaultProps.textChangeButton,
  },
  showAddButton: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.showAddButton,
  },
  showCreateButton: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.showCreateButton,
  },
  showInputText: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.showInputText,
  },
  clickable: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.clickable,
  },
  multiple: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.multiple,
  },
  inline: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.inline,
  },
  icon: {
    type: Boolean as PropType<boolean>,
    default: defaultProps.icon,
  },
});

const emit = defineEmits(['add', 'auxclick', 'click', 'create', 'delete', 'enter', 'input']);

const text = ref('');

function getImageUrl(icon?: string) {
  return icon ?? new URL(`../assets/${props.defaultIcon}.svg`, import.meta.url).href;
}

function onClick(e: MouseEvent, eventName: 'click' | 'auxclick', key: number, item: any) {
  e.preventDefault();
  emit(eventName, key, item);
}
</script>

<style module>
.inline {
  display: inline-block;
}

.title {
  position: relative;
  top: 2px;
  color: rgb(16, 102, 187);
}
</style>
