// src/components/BxRadio.vue
<template>
  <label class="ui-ctl ui-ctl-radio" :style="{ 'width': width }">
    <input
      class="ui-ctl-element"
      type="radio"
      :checked="isChecked"
      :value="value"
      :disabled="disabled"
      @change="$emit('update:modelValue', $event.target.value)"
    >
    <div class="ui-ctl-label-text">
      <slot></slot>
    </div>
  </label>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { loadStyles } from '../utils/loadStyles';

export default defineComponent({
  computed: {
    isChecked() {
      return this.modelValue === this.value;
    },
  },
  created() {
    loadStyles();
  },
  emits: ['update:modelValue'],
  props: {
    modelValue: {
      type: [Boolean, String, Array, Object],
      default: '',
    },
    value: {
      type: [Boolean, String, Array, Object],
      default: '',
    },
    width: {
      type: String,
      default: '320px',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  name: 'bx-radio',
});
</script>

<style>
.ui-ctl-radio {
  cursor: pointer;
}
</style>

// react/lib/components/BxRadio/BxRadio.tsx
import { defaultProps, type Props } from './BxRadio.props';
import styles from './BxRadio.module.css';
import { getClassName } from '../../utils/getClassName';

export function BxRadio({ children, ...props }: Partial<Props>) {
  const {
    onChange = () => null,
    value = defaultProps.value,
    name = defaultProps.name,
    checked = defaultProps.checked,
    disabled = defaultProps.disabled,
  } = props;

  return (
    <label className={getClassName('ui-ctl ui-ctl-radio', Object.values(styles))}>
      <input
        className="ui-ctl-element"
        type="radio"
        value={value}
        name={name}
        checked={checked}
        disabled={disabled}
        onChange={(e) => onChange(e)}
      />
      <div className="ui-ctl-label-text">{children}</div>
    </label>
  );
}
