// vue/src/components/BxProgressbar.vue
<template>
  <div class="ui-progressbar" :class="classList">
    <div v-if="props.textBefore" class="ui-progressbar-text-before">{{ props.textBefore }}</div>
    <div class="ui-progressbar-track">
      <div class="ui-progressbar-bar" :style="{ width }"></div>
    </div>
    <div v-if="props.textAfter" class="ui-progressbar-text-after">{{ props.textAfter }}</div>
  </div>
</template>

<script setup lang="ts">
import { computed, type PropType } from 'vue';
import { defaultProps, type PropColor, type PropSize, propsValues } from './BxProgressbar.props';
import { useStyles } from '../composable/useStyles';
import { getClassName } from '../utils/getClassName';

useStyles();

const props = defineProps({
  progress: {
    type: Number,
    default: defaultProps.progress,
    validator(value) {
      return Number.isFinite(value);
    },
  },
  size: {
    type: String as PropType<PropSize>,
    default: defaultProps.size,
    validator(value: PropSize) {
      return propsValues.sizes.includes(value);
    },
  },
  color: {
    type: String as PropType<PropColor>,
    default: defaultProps.color,
    validator(value: PropColor) {
      return propsValues.colors.includes(value);
    },
  },
  textBefore: {
    type: String,
    default: defaultProps.textBefore,
  },
  textAfter: {
    type: String,
    default: defaultProps.textAfter,
  },
  bg: {
    type: Boolean,
    default: defaultProps.bg,
  },
  column: {
    type: Boolean,
    default: defaultProps.column,
  },
});

const width = computed(() => `${props.progress}%`);

const classList = computed(() =>
  getClassName({
    [`ui-progressbar-${props.size}`]: propsValues.sizes.includes(props.size),
    [`ui-progressbar-${props.color}`]: propsValues.colors.includes(props.color),
    'ui-progressbar-bg': props.bg,
    'ui-progressbar-column': props.column,
  }),
);
</script>

// react/lib/components/BxProgressbar/BxProgressbar.tsx
import { defaultProps, type Props, propsValues } from './BxProgressbar.props';
import { type ClassListType, getClassName } from '../../utils/getClassName';

export function BxProgressbar(props: Partial<Props>) {
  const {
    progress = defaultProps.progress,
    size = defaultProps.size,
    color = defaultProps.color,
    textBefore = defaultProps.textBefore,
    textAfter = defaultProps.textAfter,
    bg = defaultProps.bg,
    column = defaultProps.column,
  } = props;

  const classList: ClassListType = {
    [`ui-progressbar-${size}`]: propsValues.sizes.includes(size),
    [`ui-progressbar-${color}`]: propsValues.colors.includes(color),
    'ui-progressbar-bg': bg,
    'ui-progressbar-column': column,
  };

  const before = <div className="ui-progressbar-text-before">{textBefore}</div>;
  const after = <div className="ui-progressbar-text-after">{textAfter}</div>;

  return (
    <div className={getClassName('ui-progressbar', classList)}>
      {before ?? ''}
      <div className="ui-progressbar-track">
        <div
          className="ui-progressbar-bar"
          style={{
            width: `${progress}%`,
          }}
        ></div>
      </div>
      {after ?? ''}
    </div>
  );
}
