// vue/src/components/BxInput.vue
<template>
  <div class="bx-input ui-ctl ui-ctl-textbox" :class="classList">
    <component
      v-if="props.beforeIcon"
      :is="props.beforeButton ? 'button' : 'div'"
      :class="classListBeforeIcon"
      @click="$emit('click-before')"
    ></component>
    <component
      v-if="props.afterIcon"
      :is="props.afterButton ? 'button' : 'div'"
      :class="classListAfterIcon"
      @click="$emit('click-after')"
    ></component>
    <div v-if="props.tag" class="ui-ctl-tag" :class="classListTag">
      {{ props.tag }}
    </div>
    <input
      type="text"
      class="ui-ctl-element"
      :value="props.modelValue"
      :placeholder="props.placeholder"
      :disabled="props.disabled"
      @input="onEmit($event, 'update:modelValue')"
      @change="onEmit($event, 'change')"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, type PropType, useCssModule } from 'vue';
import {
  defaultProps,
  propsValues,
  type PropColor,
  type PropIcon,
  type PropSize,
  type PropTagColor,
} from './BxInput.props';
import { useStyles } from '../composable/useStyles';
import { getClassName } from '../utils/getClassName';

useStyles();

const props = defineProps({
  modelValue: {
    type: String,
    default: defaultProps.value,
  },
  placeholder: {
    type: String,
    default: defaultProps.placeholder,
  },
  disabled: {
    type: Boolean,
    default: defaultProps.disabled,
  },
  size: {
    type: String as PropType<PropSize>,
    default: defaultProps.size,
    validator(value: PropSize) {
      return propsValues.sizes.includes(value);
    },
  },
  color: {
    type: String as PropType<PropColor>,
    default: defaultProps.color,
    validator(value: PropColor) {
      return propsValues.colors.includes(value);
    },
  },
  inline: {
    type: Boolean,
    default: defaultProps.inline,
  },
  noBorder: {
    type: Boolean,
    default: defaultProps.noBorder,
  },
  underline: {
    type: Boolean,
    default: defaultProps.underline,
  },
  noPadding: {
    type: Boolean,
    default: defaultProps.noPadding,
  },
  round: {
    type: Boolean,
    default: defaultProps.round,
  },
  tag: {
    type: String,
    default: defaultProps.tag,
  },
  tagColor: {
    type: String as PropType<PropTagColor>,
    default: defaultProps.tagColor,
    validator(value: PropTagColor) {
      return propsValues.tagColors.includes(value);
    },
  },
  beforeIcon: {
    type: String as PropType<PropIcon>,
    default: defaultProps.beforeIcon,
    validator(value: PropIcon) {
      return propsValues.icons.includes(value);
    },
  },
  beforeExt: {
    type: Boolean,
    default: defaultProps.beforeExt,
  },
  beforeButton: {
    type: Boolean,
    default: defaultProps.beforeButton,
  },
  afterIcon: {
    type: String as PropType<PropIcon>,
    default: defaultProps.afterIcon,
    validator(value: PropIcon) {
      return propsValues.icons.includes(value);
    },
  },
  afterExt: {
    type: Boolean,
    default: defaultProps.afterExt,
  },
  afterButton: {
    type: Boolean,
    default: defaultProps.afterButton,
  },
});

const emit = defineEmits(['update:modelValue', 'change', 'click-before', 'click-after']);

function onEmit(event: Event, eventName: 'change' | 'update:modelValue') {
  const input = event.target as HTMLInputElement;
  emit(eventName, input.value);
}

const styles = useCssModule();

const classList = computed(() =>
  getClassName({
    [`ui-ctl-${props.size}`]: propsValues.sizes.includes(props.size),
    [`ui-ctl-${props.color}`]: Boolean(props.color) && propsValues.colors.includes(props.color),
    'ui-ctl-before-icon': Boolean(props.beforeIcon) && !props.beforeExt,
    'ui-ctl-ext-before-icon': Boolean(props.beforeIcon) && props.beforeExt,
    'ui-ctl-after-icon': Boolean(props.afterIcon) && !props.afterExt,
    'ui-ctl-ext-after-icon': Boolean(props.afterIcon) && props.afterExt,
    'ui-ctl-inline': props.inline,
    'ui-ctl-no-border': props.noBorder,
    'ui-ctl-underline': props.underline,
    'ui-ctl-no-padding': props.noPadding,
    'ui-ctl-round': props.round,
    [styles['bx-input']]: true,
  }),
);

const classListBeforeIcon = computed(() =>
  getClassName({
    'ui-ctl-before': !props.beforeExt,
    'ui-ctl-ext-before': props.beforeExt,
    [`ui-ctl-icon-${props.beforeIcon}`]:
      Boolean(props.beforeIcon) && propsValues.icons.includes(props.beforeIcon),
    [styles['bx-input-before']]: true,
  }),
);

const classListAfterIcon = computed(() =>
  getClassName({
    'ui-ctl-after': !props.afterExt,
    'ui-ctl-ext-after': props.afterExt,
    [`ui-ctl-icon-${props.afterIcon}`]:
      Boolean(props.afterIcon) && propsValues.icons.includes(props.afterIcon),
  }),
);

const classListTag = computed(() =>
  getClassName({
    '--tag_light': props.tagColor === 'light',
    '--tag_light-blue': props.tagColor === 'light-blue',
  }),
);
</script>

<style module>
.bx-input {
  width: 100%;
}

.bx-input-before {
  left: 1px;
}
</style>

// react/lib/components/BxInput/BxInput.tsx
import { defaultProps, type Props, propsValues } from './BxInput.props';
import styles from './BxInput.module.css';
import { type ClassListType, getClassName } from '../../utils/getClassName';

export function BxInput(props: Partial<Props>) {
  const {
    onInput = () => null,
    onChange = () => null,
    onClickBefore = () => null,
    onClickAfter = () => null,
    value = defaultProps.value,
    placeholder = defaultProps.placeholder,
    disabled = defaultProps.disabled,
    size = defaultProps.size,
    color = defaultProps.color,
    inline = defaultProps.inline,
    noBorder = defaultProps.noBorder,
    underline = defaultProps.underline,
    noPadding = defaultProps.noPadding,
    round = defaultProps.round,
    tag = defaultProps.tag,
    tagColor = defaultProps.tagColor,
    beforeIcon = defaultProps.beforeIcon,
    beforeExt = defaultProps.beforeExt,
    beforeButton = defaultProps.beforeButton,
    afterIcon = defaultProps.afterIcon,
    afterExt = defaultProps.afterExt,
    afterButton = defaultProps.afterButton,
  } = props;

  const classList: ClassListType = {
    [`ui-ctl-${size}`]: propsValues.sizes.includes(size),
    [`ui-ctl-${color}`]: Boolean(color) && propsValues.colors.includes(color),
    'ui-ctl-before-icon': Boolean(beforeIcon) && !beforeExt,
    'ui-ctl-ext-before-icon': Boolean(beforeIcon) && beforeExt,
    'ui-ctl-after-icon': Boolean(afterIcon) && !afterExt,
    'ui-ctl-ext-after-icon': Boolean(afterIcon) && afterExt,
    'ui-ctl-inline': inline,
    'ui-ctl-no-border': noBorder,
    'ui-ctl-underline': underline,
    'ui-ctl-no-padding': noPadding,
    'ui-ctl-round': round,
    [styles['bx-input']]: true,
  };

  const classListBeforeIcon: ClassListType = {
    'ui-ctl-before': !beforeExt,
    'ui-ctl-ext-before': beforeExt,
    [`ui-ctl-icon-${beforeIcon}`]: Boolean(beforeIcon) && propsValues.icons.includes(beforeIcon),
    [styles['bx-input-before']]: true,
  };

  const classListAfterIcon: ClassListType = {
    'ui-ctl-after': !afterExt,
    'ui-ctl-ext-after': afterExt,
    [`ui-ctl-icon-${afterIcon}`]: Boolean(afterIcon) && propsValues.icons.includes(afterIcon),
  };

  const classListTag: ClassListType = {
    '--tag_light': tagColor === 'light',
    '--tag_light-blue': tagColor === 'light-blue',
  };

  const BeforeIcon = beforeButton ? (
    <button
      className={getClassName('', classListBeforeIcon)}
      onClick={(e) => onClickBefore(e)}
    ></button>
  ) : (
    <div className={getClassName('', classListBeforeIcon)}></div>
  );

  const AfterIcon = afterButton ? (
    <button
      className={getClassName('', classListAfterIcon)}
      onClick={(e) => onClickAfter(e)}
    ></button>
  ) : (
    <div className={getClassName('', classListAfterIcon)}></div>
  );

  const Tag = <div className={getClassName('ui-ctl-tag', classListTag)}>{tag}</div>;

  return (
    <div className={getClassName('ui-ctl ui-ctl-textbox', classList)}>
      {beforeIcon ? BeforeIcon : ''}
      {afterIcon ? AfterIcon : ''}
      {tag ? Tag : ''}
      <input
        type="text"
        className="ui-ctl-element"
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        onInput={(e) => onInput(e)}
        onChange={(e) => onChange(e)}
      />
    </div>
  );
}
