// react/lib/components/BxAlert/BxAlert.tsx
import { defaultProps, type Props, propsValues } from './BxAlert.props';
import { type ClassListType, getClassName } from '../../utils/getClassName';

export function BxAlert({ children, ...props }: Partial<Props>) {
  const {
    onClose = () => null,
    title = defaultProps.title,
    size = defaultProps.size,
    color = defaultProps.color,
    icon = defaultProps.icon,
    center = defaultProps.center,
    inline = defaultProps.inline,
    closing = defaultProps.closing,
  } = props;

  const classList: ClassListType = {
    [`ui-alert-${size}`]: propsValues.sizes.includes(size),
    [`ui-alert-${color}`]: propsValues.colors.includes(color),
    [`ui-alert-icon-${icon}`]: Boolean(icon) && propsValues.icons.includes(icon),
    'ui-alert-text-center': center,
    'ui-alert-inline': inline,
  };

  return (
    <div className={getClassName('ui-alert', classList)}>
      <span className="ui-alert-message">
        {title ? <strong>{title}</strong> : ''} {children}
      </span>
      {closing ? <span className="ui-alert-close-btn" onClick={(e) => onClose(e)}></span> : ''}
    </div>
  );
}

// src/components/BxAlert.vue
<template>
  <div class="ui-alert" :class="classList">
    <span class="ui-alert-message">
      <strong v-if="title"> {{ title }} </strong>
      <slot></slot>
    </span>
    <span class="ui-alert-close-btn" @click="$emit('close')"></span>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { loadStyles } from '../utils/loadStyles';

export const props = {
  sizes: ['md', 'xs'],
  colors: ['default', 'primary', 'success', 'warning', 'danger'],
  icons: ['', 'warning', 'danger', 'info'],
};

export default defineComponent({
  computed: {
    classList() {
      return {
        [`ui-alert-${this.size}`]: props.sizes.includes(this.size),
        [`ui-alert-${this.color}`]: props.colors.includes(this.color),
        [`ui-alert-icon-${this.icon}`]: this.icon && props.icons.includes(this.icon),
        'ui-alert-text-center': this.center,
        'ui-alert-inline': this.inline,
      };
    },
  },
  created() {
    loadStyles();
  },
  emits: ['close'],
  props: {
    title: {
      type: String,
      default: 'Внимание!',
      validator(value) {
        return typeof value === 'string';
      },
    },
    size: {
      type: String,
      default: 'md',
      validator(value) {
        return typeof value === 'string' && props.sizes.includes(value);
      },
    },
    color: {
      type: String,
      default: 'default',
      validator(value) {
        return typeof value === 'string' && props.colors.includes(value);
      },
    },
    icon: {
      type: String,
      default: '',
      validator(value) {
        return typeof value === 'string' && props.icons.includes(value);
      },
    },
    center: {
      type: Boolean,
      default: false,
    },
    inline: {
      type: Boolean,
      default: false,
    },
  },
  name: 'bx-alert',
});
</script>
