// react/lib/components/BxProgressbar/BxProgressbar.tsx
import { defaultProps, type Props, propsValues } from './BxProgressbar.props';
import { type ClassListType, getClassName } from '../../utils/getClassName';

export function BxProgressbar(props: Partial<Props>) {
  const {
    progress = defaultProps.progress,
    size = defaultProps.size,
    color = defaultProps.color,
    textBefore = defaultProps.textBefore,
    textAfter = defaultProps.textAfter,
    bg = defaultProps.bg,
    column = defaultProps.column,
  } = props;

  const classList: ClassListType = {
    [`ui-progressbar-${size}`]: propsValues.sizes.includes(size),
    [`ui-progressbar-${color}`]: propsValues.colors.includes(color),
    'ui-progressbar-bg': bg,
    'ui-progressbar-column': column,
  };

  const before = <div className="ui-progressbar-text-before">{textBefore}</div>;
  const after = <div className="ui-progressbar-text-after">{textAfter}</div>;

  return (
    <div className={getClassName('ui-progressbar', classList)}>
      {before ?? ''}
      <div className="ui-progressbar-track">
        <div
          className="ui-progressbar-bar"
          style={{
            width: `${progress}%`,
          }}
        ></div>
      </div>
      {after ?? ''}
    </div>
  );
}

// src/components/BxProgressbar.vue
<template>
  <div class="ui-progressbar" :class="classList">
    <div v-if="textBefore" class="ui-progressbar-text-before">{{ textBefore }}</div>
    <div class="ui-progressbar-track">
      <div class="ui-progressbar-bar" :style="{ width }"></div>
    </div>
    <div v-if="textAfter" class="ui-progressbar-text-after">{{ textAfter }}</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { loadStyles } from '../utils/loadStyles';

export const props = {
  sizes: ['md', 'lg'],
  colors: ['primary', 'success', 'warning', 'danger'],
};

export default defineComponent({
  computed: {
    width() {
      return `${this.progress}%`;
    },
    classList() {
      return {
        [`ui-progressbar-${this.size}`]: props.sizes.includes(this.size),
        [`ui-progressbar-${this.color}`]: props.colors.includes(this.color),
        'ui-progressbar-bg': this.bg,
        'ui-progressbar-column': this.column,
      };
    },
  },
  created() {
    loadStyles();
  },
  props: {
    progress: {
      type: Number,
      default: 0,
      validator(value) {
        return Number.isFinite(value);
      },
    },
    size: {
      type: String,
      default: 'md',
      validator(value) {
        return props.sizes.includes(value);
      },
    },
    color: {
      type: String,
      default: 'primary',
      validator(value) {
        return props.colors.includes(value);
      },
    },
    textBefore: {
      type: String,
      default: '',
    },
    textAfter: {
      type: String,
      default: '',
    },
    bg: {
      type: Boolean,
      default: false,
    },
    column: {
      type: Boolean,
      default: false,
    },
  },
  name: 'bx-progressbar',
});
</script>
