// src/components/BxTextarea.vue
<template>
  <div
    class="ui-ctl ui-ctl-textarea"
    :class="{
      'ui-ctl-no-resize': resize === 'no',
      'ui-ctl-resize-y': resize === 'y',
      'ui-ctl-resize-x': resize === 'x',
    }"
  >
    <textarea
      class="ui-ctl-element"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      @input="$emit('update:modelValue', $event.target.value)"
    ></textarea>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  emits: ['update:modelValue'],
  props: {
    modelValue: {
      type: String,
      default: '',
    },
    placeholder: {
      type: String,
      default: '',
    },
    resize: {
      type: String,
      default: '',
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  },
  name: 'bx-textarea',
});
</script>

// react/lib/components/BxTextarea/BxTextarea.tsx
import { defaultProps, type Props } from './BxTextarea.props';
import { type ClassListType, getClassName } from '../../utils/getClassName';

export function BxTextarea(props: Partial<Props>) {
  const {
    onInput = () => null,
    value = defaultProps.value,
    placeholder = defaultProps.placeholder,
    resize = defaultProps.resize,
    disabled = defaultProps.disabled,
  } = props;

  const classList: ClassListType = {
    'ui-ctl-no-resize': resize === 'no',
    'ui-ctl-resize-y': resize === 'y',
    'ui-ctl-resize-x': resize === 'x',
  };

  return (
    <div className={getClassName('ui-ctl ui-ctl-textarea', classList)}>
      <textarea
        className="ui-ctl-element"
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        onInput={(e) => onInput(e)}
      ></textarea>
    </div>
  );
}
