// vue/src/components/BxTextarea.vue
<template>
  <div
    class="ui-ctl ui-ctl-textarea"
    :class="{
      'ui-ctl-no-resize': props.resize === 'no',
      'ui-ctl-resize-y': props.resize === 'y',
      'ui-ctl-resize-x': props.resize === 'x',
    }"
  >
    <textarea
      class="ui-ctl-element"
      :value="props.modelValue"
      :placeholder="props.placeholder"
      :disabled="props.disabled"
      @input="onInput"
    ></textarea>
  </div>
</template>

<script setup lang="ts">
import type { PropType } from 'vue';
import { defaultProps, type PropResize, propsValues } from './BxTextarea.props';
import { useStyles } from '../composable/useStyles';

useStyles();

const props = defineProps({
  modelValue: {
    type: String,
    default: defaultProps.value,
  },
  placeholder: {
    type: String,
    default: defaultProps.placeholder,
  },
  resize: {
    type: String as PropType<PropResize>,
    default: defaultProps.resize,
    validator(value: PropResize) {
      return propsValues.resizes.includes(value);
    },
  },
  disabled: {
    type: Boolean,
    default: defaultProps.disabled,
  },
});

const emit = defineEmits(['update:modelValue']);

function onInput(event: Event) {
  const input = event.target as HTMLInputElement;
  emit('update:modelValue', input.value);
}
</script>

// react/lib/components/BxTextarea/BxTextarea.tsx
import { defaultProps, type Props } from './BxTextarea.props';
import { type ClassListType, getClassName } from '../../utils/getClassName';

export function BxTextarea(props: Partial<Props>) {
  const {
    onInput = () => null,
    value = defaultProps.value,
    placeholder = defaultProps.placeholder,
    resize = defaultProps.resize,
    disabled = defaultProps.disabled,
  } = props;

  const classList: ClassListType = {
    'ui-ctl-no-resize': resize === 'no',
    'ui-ctl-resize-y': resize === 'y',
    'ui-ctl-resize-x': resize === 'x',
  };

  return (
    <div className={getClassName('ui-ctl ui-ctl-textarea', classList)}>
      <textarea
        className="ui-ctl-element"
        value={value}
        placeholder={placeholder}
        disabled={disabled}
        onInput={(e) => onInput(e)}
      ></textarea>
    </div>
  );
}
