// vue/src/components/BxEntitySelector.vue
<template>
  <div :class="[$style['bx-entity-selector'], { [$style['inline']]: props.inline }]">
    <div :class="$style['bx-entity-selector__button']">
      <span :class="$style['bx-entity-selector__items']">
        <span
          v-for="(item, key) in props.list"
          :key="key"
          :class="[
            $style['bx-entity-selector__item'],
            { [$style['hover-delete']]: data.hoverDelete[key] },
          ]"
        >
          <a
            v-if="props.clickable"
            :href="item[displayFieldLink]"
            target="_blank"
            :class="$style['bx-entity-selector__text']"
            @click="onClick($event, key, item, 'click')"
            @auxclick="onClick($event, key, item, 'auxclick')"
          >
            {{ item[displayField] }}
          </a>
          <span v-else :class="$style['bx-entity-selector__text']">
            {{ item[displayField] }}
          </span>
          <button
            :class="$style['bx-entity-selector__delete']"
            @mouseenter="data.hoverDelete[key] = true"
            @mouseleave="data.hoverDelete[key] = false"
            @click="$emit('delete', key, item)"
          ></button>
        </span>
      </span>
      <span :class="$style['bx-entity-selector__controls']">
        <button :class="$style['bx-entity-selector__add']" @click="$emit('add')">
          {{
            !props.list.length ? props.textAdd : props.multiple ? props.textMore : props.textChange
          }}
        </button>
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, type PropType } from 'vue';
import { defaultProps } from './BxEntitySelector.props';

const props = defineProps({
  list: {
    type: Array as PropType<any[]>,
    default: () => defaultProps.list,
  },
  displayField: {
    type: String,
    default: defaultProps.displayField,
  },
  displayFieldLink: {
    type: String,
    default: defaultProps.displayFieldLink,
  },
  textAdd: {
    type: String,
    default: defaultProps.textAdd,
  },
  textMore: {
    type: String,
    default: defaultProps.textMore,
  },
  textChange: {
    type: String,
    default: defaultProps.textChange,
  },
  clickable: {
    type: Boolean,
    default: defaultProps.clickable,
  },
  multiple: {
    type: Boolean,
    default: defaultProps.multiple,
  },
  inline: {
    type: Boolean,
    default: defaultProps.inline,
  },
});

const emit = defineEmits(['add', 'click', 'auxclick', 'delete']);

const data = reactive({
  hoverDelete: [] as boolean[],
});

function onClick(e: MouseEvent, key: number, item: any, eventName: 'click' | 'auxclick') {
  if (props.clickable) {
    e.preventDefault();
    emit(eventName, key, item);
  }
}
</script>

<style module>
.bx-entity-selector {
  font-family: sans-serif;
}

.bx-entity-selector.inline {
  display: inline-block;
}

.bx-entity-selector__button {
  background-color: #fff;
  min-height: 33px;
  border: 1px solid #c6cdd3;
  padding: 5px 5px 0 5px;
}

.bx-entity-selector__item {
  background-color: #bcedfc;
  transition: background-color 0.2s linear;
  display: inline-block;
  overflow: hidden;
  vertical-align: middle;
  white-space: nowrap;
  height: 30px;
  position: relative;
  line-height: 28px;
  margin: 0 5px 5px 0;
}

.bx-entity-selector__item.hover-delete {
  background-color: #8be0fa;
}

.bx-entity-selector__text {
  padding: 0 0 0 10px;
  display: inline-block;
  max-width: 250px;
  overflow: hidden;
  text-overflow: ellipsis;
  vertical-align: middle;
  font-weight: bold;
  font-size: 13px;
  text-decoration: none;
  color: #1f6ab5;
}

.bx-entity-selector__delete {
  background-color: transparent;
  border: none;
  padding: 0;
  font-family: inherit;
  width: 25px;
  height: 30px;
  z-index: 1;
  cursor: pointer;
  display: inline-block;
  vertical-align: middle;
  position: relative;
  margin: auto;
  white-space: nowrap;
  line-height: 30px;
}

.bx-entity-selector__delete::after {
  content: '';
  background-image: url('../assets/media.png');
  background-repeat: no-repeat;
  background-position: -2px -17px;
  width: 6px;
  height: 6px;
  position: absolute;
  top: 1px;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto auto auto 7px;
  opacity: 0.2;
}

.bx-entity-selector__add {
  background-color: transparent;
  border: none;
  padding: 0;
  font-family: inherit;
  margin: 7px 7px 7px 18px;
  border-bottom: 1px solid transparent;
  color: #2067b0;
  cursor: pointer;
  display: inline-block;
  font-weight: bold;
  font-size: 13px;
  line-height: 17px;
  vertical-align: top;
  position: relative;
  transition: border-bottom-color 0.2s linear;
}

.bx-entity-selector__add:hover {
  border-bottom: 1px solid;
}

.bx-entity-selector__add::before {
  content: '';
  background-image: url('../assets/add.png');
  background-repeat: no-repeat;
  background-position: center;
  height: 8px;
  left: -14px;
  position: absolute;
  top: 5px;
  width: 8px;
}
</style>

// react/lib/components/BxEntitySelector/BxEntitySelector.tsx
import React from 'react';
import { defaultProps, type Props } from './BxEntitySelector.props';
import styles from './BxEntitySelector.module.css';
import { getClassName } from '../../utils/getClassName';

export function BxEntitySelector(props: Partial<Props>) {
  const {
    onClick = () => null,
    onAuxClick = () => null,
    onAdd = () => null,
    onDelete = () => null,
    list = defaultProps.list,
    displayField = defaultProps.displayField,
    displayFieldLink = defaultProps.displayFieldLink,
    textAdd = defaultProps.textAdd,
    textMore = defaultProps.textMore,
    textChange = defaultProps.textChange,
    clickable = defaultProps.clickable,
    multiple = defaultProps.multiple,
    inline = defaultProps.inline,
  } = props;
  const [hoverDelete, setHoverDelete] = React.useState<boolean[]>([]);

  function onHover(key: number, action: boolean) {
    const arrayHover = [...hoverDelete];
    arrayHover[key] = action;
    setHoverDelete(arrayHover);
  }

  function onClickLink(
    e: React.MouseEvent,
    key: number,
    item: any,
    eventName: 'click' | 'auxclick',
  ) {
    if (clickable) {
      e.preventDefault();
      if (eventName === 'click') {
        onClick(key, item);
      } else if (eventName === 'auxclick') {
        onAuxClick(key, item);
      }
    }
  }

  const Items = list.map((item: any, key: number) => (
    <span
      className={getClassName(styles['bx-entity-selector__item'], {
        [styles['hover-delete']]: hoverDelete[key],
      })}
      key={key}
    >
      {clickable ? (
        <a
          className={styles['bx-entity-selector__text']}
          href={item[displayFieldLink]}
          target="_blank"
          onClick={(e) => onClickLink(e, key, item, 'click')}
          onAuxClick={(e) => onClickLink(e, key, item, 'auxclick')}
        >
          {item[displayField]}
        </a>
      ) : (
        <span className={styles['bx-entity-selector__text']}>{item[displayField]}</span>
      )}
      <button
        className={styles['bx-entity-selector__delete']}
        onMouseEnter={() => onHover(key, true)}
        onMouseLeave={() => onHover(key, false)}
        onClick={() => onDelete(key, item)}
      ></button>
    </span>
  ));

  return (
    <div className={getClassName(styles['bx-entity-selector'], { [styles.inline]: inline })}>
      <div className={styles['bx-entity-selector__button']}>
        <span className="bx-entity-selector__items">{Items}</span>
        <span className="bx-entity-selector__controls">
          <button className={styles['bx-entity-selector__add']} onClick={() => onAdd()}>
            {!list.length ? textAdd : multiple ? textMore : textChange}
          </button>
        </span>
      </div>
    </div>
  );
}
